name: toleka
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  animated_text_kit: ^4.1.5 
  dio: ^5.7.0
  flutter_bloc: ^8.1.6
  get: ^4.6.5
  lottie: ^3.1.3
  http: ^1.2.2
  flutter_localization: ^0.1.9
  url_launcher: ^6.1.10
  toast: ^0.3.0
  animator: ^3.0.0
  provider: ^6.0.5
  adaptive_theme: ^3.1.1
  flutter_native_image: ^0.0.6+1
  auto_layout: ^1.0.5
  google_maps_flutter: ^2.0.6
  flutter_svg: ^1.1.6
  #dio_http_cache: ^0.3.0
  firebase_core: ^2.4.1
  country_picker: ^2.0.19
  flutter_otp_text_field: ^1.1.1
  share_plus: ^6.3.1
  firebase_storage: ^11.0.14
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  bot_toast: ^4.1.3
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  #email_launcher: ^1.1.1
  email_validator: ^2.1.17
  roundcheckbox: ^2.0.5
  webview_flutter: ^4.0.2
  image_cropper: ^1.5.1
  image_picker: ^0.8.5
  animate_do: ^3.0.2
  multi_select_flutter: ^4.1.3
  flutter_launcher_icons: ^0.14.1
  flutter_native_splash: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  #flutter_launcher_icon : any
  #flutter_native_splash: any

#flutter_launcher_icons:
  #android: "launcher_icon"
  #ios: true
  #image_path: "assets/images/splash.png"
  #background_color: "#ffffff"


#flutter_native_splash:
  #image: "assets/images/splash.png"
  #color: "#ffffff"
  #android_12:
    #image: "assets/images/splash.png"



# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    #- assets/images/splash.png
    - assets/icons/
    - assets/images/
