part of 'signup_cubit.dart';

class SignupState {
  Map? field;
  SignupState({required this.field});
}

Map? initialState() {
  return {
    'id': "",
    'nom': "",
    'postnom': "",
    'prenom': "",
    'email' : "",
    'adresse' : "",
    'dataUser' : {},
    'nomparentcomplet': "",
    'universiteData': [],
    'provinceData': [],
    'villeData': [],
    'communeData': [],
    "universite": "",
    'faculteData': [],
    'faculte': "",
    'departementData': [],
    'departement': "",
    'promotionData': [],
    'ecoleData': [],
    'arretDatakelasi': [],
    'lignesDatakelasi': [],
    'dataParent': {},
    'infoEncadreur' : {},
    'arrets': "",
    'lignes': "",
    'opstudent': "",
    'promotion': "",
    'currency': "",
    'phone': "",
    'personneref': "",
    'phonePayment': "",
    'matricule': "",
    'password': "toleka@106",
    'oldPassword': "",
    'newPassword': "",
    'nomcomplet': "",
    'adressecomplete': "",
    'confirmPassword': "",
    'sexe': "",
    'dateNaissance': "",
    'commune': "",
    'quartier': "",
    'avenue': "",
    'numeroAdresse': "",
    'province': "",
    'numeroTelephone': "",
    'lieuNaissance': "",
    'codeEtudiant': "",
    'typePayment': "",
    'iconVersion': "",
    'titreVersion': "",
    'course': "",
    'date': "",
    'filePath': "",
    'photo': "",
    'imageCourse': "",
    'prixUSD': "",
    'prixCDF': "",
    'selectedIndex': "",
    'status': "",
    'typePaymentFromApi': "",
    'abonnement': "",
    'phonePayement': "",
    'code': "",
    'refresh': "",
    'day': "",
    'hours': "",
    'valueAbonnement': "",
    'descriptionVersion': "",
    'disponibility': "",
    'inputVisible': "",
    'codetransaction': "",
    "kelasiActiveIndex": "",
    "provinceDataKelasi": [],
    "villeDataKelasi": [],
    "communeDataKelasi": [],
    "serviceDataKelasi": [],
    "servicesList": [],
    "PersonneRefData": [],
    'provinceKelasi': "",
    "ecole": "",
    "sectionData": [],
    "section": "",
    "optionData": [],
    "option": "",
    "levelData": [],
    "itineraireData": [],
    "enfantData": [],
    "enfant": "",
    'operateur': "",
    'operateurData': [],
    "level": "",
    "idStudent": "",
    "userId": "",
    "parentId": "",
    "parentuuid": "",
    "parentasuser": "",
    "fromSingup": "false",
    "nomError": "",
    "postnomError": "",
    "prenomError": "",
    "sexeError": "",
    "emailError": "",
    "passwordError": "",
    "confirmPasswordError": "",
    "nombreEnfant": "",
    "provinceDataTac": [],
    "villeDataTac": [],
    "communeDataTac": [],
    "provinceTac": "",
    "villeTac": "",
    "communeTac": "",
    "statutCarte": "",
    'slides': [
      {
        "_id": "641056cb5792d792918755a4",
        "url":
            "https://firebasestorage.googleapis.com/v0/b/trans-academia.appspot.com/o/profiles%2Fcarousel-1.jpeg?alt=media&token=51501e3d-f04d-4382-8329-015c45e8cf95",
        "title": "slide 1",
        "createdAt": "2023-03-14T11:13:15.947Z",
        "updatedAt": "2023-03-14T11:13:15.947Z",
        "__v": 0
      },
    ]
  };
}
