// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1Nm-4OWelbfnOy-4Ijj9iRSq1o7VdwFE',
    appId: '1:462205201821:web:6177549a7cedb7e2641374',
    messagingSenderId: '462205201821',
    projectId: 'trans-academia',
    authDomain: 'trans-academia.firebaseapp.com',
    storageBucket: 'trans-academia.appspot.com',
    measurementId: 'G-NGKL98FQ5J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCR6SUDcw2trA8hny8AuWqZIGd0ctpFTQA',
    appId: '1:462205201821:android:1085d6b3ce3a189e641374',
    messagingSenderId: '462205201821',
    projectId: 'trans-academia',
    storageBucket: 'trans-academia.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBiPRnYG8jpx9pqGlgh6BtJbU5tCcqHeeg',
    appId: '1:462205201821:ios:12e99f2d04b31a75641374',
    messagingSenderId: '462205201821',
    projectId: 'trans-academia',
    storageBucket: 'trans-academia.appspot.com',
    iosClientId: '462205201821-6edb2458rkjjg6f6ltbgo9vrveg08k7v.apps.googleusercontent.com',
    iosBundleId: 'com.tac.kelasi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBiPRnYG8jpx9pqGlgh6BtJbU5tCcqHeeg',
    appId: '1:462205201821:ios:12e99f2d04b31a75641374',
    messagingSenderId: '462205201821',
    projectId: 'trans-academia',
    storageBucket: 'trans-academia.appspot.com',
    iosClientId: '462205201821-6edb2458rkjjg6f6ltbgo9vrveg08k7v.apps.googleusercontent.com',
    iosBundleId: 'com.tac.kelasi',
  );
}
